apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: sqlinstances.gcp.platform.upbound.io
spec:
  scope: Namespaced
  group: gcp.platform.upbound.io
  names:
    kind: SQLInstance
    plural: sqlinstances
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    managementPolicies:
                      description: "ManagementPolicies for resources. Defaults to [\"*\"] which includes all operations (Create, Observe, Update, Delete, LateInitialize). To orphan resources on deletion, use [\"Create\", \"Observe\", \"Update\", \"LateInitialize\"]."
                      type: array
                      items:
                        type: string
                        enum:
                          - "*"
                          - Create
                          - Observe
                          - Update
                          - Delete
                          - LateInitialize
                      default: ["*"]
                    providerConfigName:
                      description: Crossplane ProviderConfig to use for provisioning this resources
                      type: string
                      default: default
                    region:
                      type: string
                      description: Region is the region you'd like your resource to be created in.
                    engine:
                      type: string
                      description: This SQLInstance engine
                      enum:
                        - postgres
                        - mysql
                    engineVersion:
                      type: string
                      description: This SQLInstance engine version
                    storageGB:
                      type: integer
                    passwordSecretRef:
                      type: object
                      description: "A reference to the Secret object containing database password. In v2, namespace is inferred from the resource namespace if not specified."
                      properties:
                        namespace:
                          type: string
                          description: "Optional - namespace is inferred from resource namespace in v2"
                        name:
                          type: string
                        key:
                          type: string
                      required:
                        - name
                        - key
                    networkRef:
                      type: object
                      description: "A reference to the Network object that this postgres should be
                      connected to."
                      properties:
                        id:
                          type: string
                          description: ID of the Network object this ref points to.
                      required:
                        - id
                  required:
                    - region
                    - storageGB
                    - networkRef
                    - passwordSecretRef
              required:
                - parameters
