apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: configuration-gcp-database
  annotations:
    meta.crossplane.io/maintainer: Upbound <support@upbound.io>
    meta.crossplane.io/source: github.com/upbound/configuration-gcp-database
    meta.crossplane.io/license: Apache-2.0

spec:
  crossplane:
    version: ">=v1.14.1-0"
  dependsOn:
    - provider: xpkg.upbound.io/upbound/provider-gcp-sql
      # renovate: datasource=github-releases depName=upbound/provider-gcp
      version: "v0.41.0"
    - provider: xpkg.upbound.io/upbound/provider-gcp-servicenetworking
      # renovate: datasource=github-releases depName=upbound/provider-gcp
      version: "v0.41.0"
    - configuration: xpkg.upbound.io/upbound/configuration-gcp-network
      # renovate: datasource=github-releases depName=upbound/configuration-gcp-network
      version: "v0.1.0"
