apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xsqlinstances.gcp.platform.upbound.io
  labels:
    provider: gcp
spec:
  writeConnectionSecretsToNamespace: upbound-system
  compositeTypeRef:
    apiVersion: gcp.platform.upbound.io/v1alpha1
    kind: XSQLInstance
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: crossplane-contrib-function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        patchSets:
          - name: providerConfigRef
            patches:
              - fromFieldPath: spec.parameters.providerConfigName
                toFieldPath: spec.providerConfigRef.name
                type: FromCompositeFieldPath
          - name: deletionPolicy
            patches:
              - fromFieldPath: spec.parameters.deletionPolicy
                toFieldPath: spec.deletionPolicy
                type: FromCompositeFieldPath
          - name: region
            patches:
              - fromFieldPath: spec.parameters.region
                toFieldPath: spec.forProvider.region
                type: FromCompositeFieldPath
        resources:
          - name: PrivateIPAddress
            base:
              apiVersion: compute.gcp.upbound.io/v1beta1
              kind: GlobalAddress
              spec:
                forProvider:
                  addressType: INTERNAL
                  prefixLength: 16
                  purpose: VPC_PEERING
            patches:
              - type: PatchSet
                patchSetName: providerConfigRef
              - type: PatchSet
                patchSetName: deletionPolicy
              - fromFieldPath: spec.parameters.networkRef.id
                toFieldPath: spec.forProvider.networkSelector.matchLabels[networks.gcp.platform.upbound.io/network-id]
          - name: PrivateConnection
            base:
              apiVersion: servicenetworking.gcp.upbound.io/v1beta1
              kind: Connection
              spec:
                forProvider:
                  reservedPeeringRangesSelector:
                    matchControllerRef: true
                  service: servicenetworking.googleapis.com
                  updateOnCreationFail: true
            patches:
              - type: PatchSet
                patchSetName: providerConfigRef
              - type: PatchSet
                patchSetName: deletionPolicy
              - fromFieldPath: spec.parameters.networkRef.id
                toFieldPath: spec.forProvider.networkSelector.matchLabels[networks.gcp.platform.upbound.io/network-id]
          - name: DatabaseUser
            base:
              apiVersion: sql.gcp.upbound.io/v1beta1
              kind: User
              spec:
                forProvider:
                  instanceSelector:
                    matchControllerRef: true
            patches:
              - type: PatchSet
                patchSetName: providerConfigRef
              - type: PatchSet
                patchSetName: deletionPolicy
              - fromFieldPath: spec.parameters.passwordSecretRef.namespace
                toFieldPath: spec.forProvider.passwordSecretRef.namespace
              - fromFieldPath: spec.parameters.passwordSecretRef.name
                toFieldPath: spec.forProvider.passwordSecretRef.name
              - fromFieldPath: spec.parameters.passwordSecretRef.key
                toFieldPath: spec.forProvider.passwordSecretRef.key
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: spec.parameters.engine
                    - fromFieldPath: metadata.uid
                  strategy: string
                  string:
                    fmt: "%suser-%.8s"  # mysql has a limit of 32 chars for users thus we need to limit the length
                toFieldPath: metadata.annotations[crossplane.io/external-name]
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: metadata.uid
                    - fromFieldPath: spec.parameters.engine
                  strategy: string
                  string:
                    fmt: "%s-gcp-%s-user"
                toFieldPath: spec.writeConnectionSecretToRef.name
              - fromFieldPath: spec.writeConnectionSecretToRef.namespace
                toFieldPath: spec.writeConnectionSecretToRef.namespace
            connectionDetails:
              - name: username
                type: FromFieldPath
                fromFieldPath: metadata.annotations[crossplane.io/external-name]
              - name: password
                type: FromConnectionSecretKey
                fromConnectionSecretKey: attribute.password
          - name: UpboundDatabase
            base:
              apiVersion: sql.gcp.upbound.io/v1beta1
              kind: Database
              spec:
                forProvider:
                  instanceSelector:
                    matchControllerRef: true
            patches:
              - type: PatchSet
                patchSetName: providerConfigRef
              - type: PatchSet
                patchSetName: deletionPolicy
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.name
                toFieldPath: metadata.annotations[crossplane.io/external-name]
                transforms:
                  - type: match
                    match:
                      fallbackValue: null
                      patterns:
                        - regexp: .*
                          result: upbound
                          type: regexp
          - name: DBInstance
            base:
              apiVersion: sql.gcp.upbound.io/v1beta1
              kind: DatabaseInstance
              spec:
                forProvider:
                  deletionProtection: false
                  settings:
                    - diskSize: 20
                      tier: db-f1-micro
                      ipConfiguration:
                        - ipv4Enabled: false
            patches:
              - type: PatchSet
                patchSetName: providerConfigRef
              - type: PatchSet
                patchSetName: deletionPolicy
              - type: PatchSet
                patchSetName: region
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: metadata.uid
                    - fromFieldPath: spec.parameters.engine
                  strategy: string
                  string:
                    fmt: "%s-gcp-%s"
                toFieldPath: spec.writeConnectionSecretToRef.name
              - fromFieldPath: spec.writeConnectionSecretToRef.namespace
                toFieldPath: spec.writeConnectionSecretToRef.namespace
              - fromFieldPath: spec.parameters.storageGB
                toFieldPath: spec.forProvider.settings[0].diskSize
              - fromFieldPath: spec.parameters.networkRef.id
                toFieldPath: spec.forProvider.settings[0].ipConfiguration[0].privateNetworkRef.name
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: spec.parameters.engine
                    - fromFieldPath: spec.parameters.engineVersion
                  strategy: string
                  string:
                    fmt: "%s_%s"
                toFieldPath: spec.forProvider.databaseVersion
                transforms:
                  - type: string
                    string:
                      type: Convert
                      convert: "ToUpper"
            connectionDetails:
              - name: host
                type: FromConnectionSecretKey
                fromConnectionSecretKey: privateIP
              - name: serverCACertificateCert
                type: FromConnectionSecretKey
                fromConnectionSecretKey: serverCACertificateCert

    - step: sequence-creation
      functionRef:
        name: crossplane-contrib-function-sequencer
      input:
        apiVersion: sequencer.fn.crossplane.io/v1beta1
        kind: Input
        rules:
          - sequence:
              - PrivateIPAddress
              - PrivateConnection
              - DBInstance
              - DatabaseUser
              - UpboundDatabase
